AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - 'national-holidays-config/**/*.rb'

Metrics/LineLength:
  Enabled: false

Metrics/BlockLength:
  Max: 80

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Max: 50

Style/Documentation:
  Enabled: false
